config/routes.rb
Ultra::Application.routes.draw do

root "categs#index"

resources :categs, :subcategs, :pages, :posts, :comments
resources :posts, comments: :commentable
resources :pages, comments: :commentable

end

app/models/categ.rb
# == Schema Information
#
# Table name: categs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Categ < ActiveRecord::Base
  validates :name,  presence: true, length: {maximum: 60 }
  has_many :subcategs
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  validates :body,  presence: true, length: {maximum: 140 }
  belongs_to :commentable, polymorphic: true
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Page < ActiveRecord::Base
  validates :name,  presence: true, length: {maximum: 140 }
  validates :body,  presence: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  year       :integer
#  body       :text
#  size       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :name,  presence: true, length: {maximum: 140 }
  validates :year,  numericality: { only_integer: true, greater_than: 0, less_than: 2014 }
  validates :body,  presence: true
  validates :size,  presence: true
  has_and_belongs_to_many :subcategs
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/subcateg.rb
# == Schema Information
#
# Table name: subcategs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  categ_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Subcateg < ActiveRecord::Base
  validates :name,  presence: true, length: {maximum: 60 }
  belongs_to :categ
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def render_404
    respond_to do |format|
      format.html { render file: :"#{Rails.root}/public/404", status: 404, layout: false }
    end
  end

end

app/controllers/categs_controller.rb
class CategsController < ApplicationController

before_filter :find_categ,  only: [:show, :edit, :update, :destroy]

  def index
    @categs = Categ.all
  end

  def show
  end

  def new
    @categ = Categ.new
  end

  def edit
  end

  def create
    @categ = Categ.create(categ_param)
    if @categ.errors.empty?
      redirect_to categ_path(@categ)
    else
      flash.now[:error] = "You made mistakes."
      render "new"
    end
  end

  def update
    @categ.update_attributes(categ_param)
    if @categ.errors.empty?
      redirect_to categ_path(@categ)
    else
      flash.now[:error] = "You made mistakes."
      render "edit"
    end
  end

  def destroy
    @categ.destroy
    redirect_to action: "index"
  end

private
  def categ_param
    params.require(:categ).permit(:name)
  end

  def find_categ
    @categ = Categ.find(params[:id])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :find_comment,  only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
    unless @comment
      render text: "Page not found", status: 404
    end
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.create(comment_param)
    if @comment.errors.empty?
      redirect_to comment_path(@comment)
    else
      flash.now[:error] = "You made mistakes."
      render "new"
    end
  end

  def update
    @comment.update_attributes(comment_param)
    if @comment.errors.empty?
      redirect_to comment_path(@comment)
    else
      render "edit"
    end
  end

  def destroy
    @comment.destroy
    redirect_to action: "index"
  end

private
  def comment_param
    params.require(:comment).permit(:body)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

before_filter :find_page,  only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
    unless @page
      render text: "Page not found", status: 404
    end
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.create(page_param)
    if @page.errors.empty?
      redirect_to page_path(@page)
    else
      flash.now[:error] = "You made mistakes."
      render "new"
    end
  end

  def update
    @page.update_attributes(page_param)
    if @page.errors.empty?
      redirect_to page_path(@page)
    else
      flash.now[:error] = "You made mistakes."
      render "edit"
    end
  end

  def destroy
    @page.destroy
    redirect_to action: "index"
  end

private
  def page_param
    params.require(:page).permit(:name, :body)
  end

  def find_page
    @page = Page.find(params[:id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_filter :find_post,  only: [ :show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    unless @post
      render text: "Page not found", status: 404
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.create(post_param)
    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      flash.now[:error] = "You made mistakes."
      render "new"
    end
  end

  def update
    @post.update_attributes(post_param)
    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      flash.now[:error] = "You made mistakes."
      render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to action: "index"
  end

  private
  def post_param
    params.require(:post).permit(:name, :year, :body, :size)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/subcategs_controller.rb
class SubcategsController < ApplicationController

before_filter :find_subcateg,  only: [:show, :edit, :update, :destroy]

  def index
    @subcategs = Subcateg.all
  end

  def show
    unless @subcateg
      render text: "Page not found", status: 404
    end
  end

  def new
    @subcateg = Subcateg.new
  end

  def edit
  end

  def create
    @subcateg = Subcateg.create(subcateg_param)
    if @subcateg.errors.empty?
      redirect_to subcateg_path(@subcateg)
    else
      flash.now[:error] = "You made mistakes."
      render "new"
    end
  end

  def update
    @subcateg.update_attributes(subcateg_param)
    if @subcateg.errors.empty?
      redirect_to subcateg_path(@subcateg)
    else
      flash.now[:error] = "You made mistakes."
      render "edit"
    end
  end

  def destroy
    @subcateg.destroy
    redirect_to action: "index"
  end

  private
  def subcateg_param
    params.require(:subcateg).permit(:name)
  end

  def find_subcateg
    @subcateg = Subcateg.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categs_helper.rb
module CategsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subcategs_helper.rb
module SubcategsHelper
end

app/views/categs/_form.html.haml
%p
  Name of category:
  %br/
  = f.text_field :name

app/views/categs/_notifications.html.haml
%p{style: "color: red;"}
  = flash[:error]

app/views/categs/edit.html.erb
<h1>Edit category</h1>

<%= form_for @categ do |f| %>

 <p>Name of category: <br/><%= f.text_field :name %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/categs/edit.html.haml
%h1 Edit category
= render partial: "notifications"
= form_for @categ do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Save"

app/views/categs/index.html.erb
<% @categs.each do |i| %>

  <p><%= link_to i.name, categ_path(i) %> <%= link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} %></p>

<% end %>

app/views/categs/index.html.haml
- @categs.each do |i|
  %h1
    = link_to i.name, categ_path(i)
  /
    <haml_loud> link_to 'Edit', edit_categ_path(i) </haml_loud>
    <haml_loud> link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} </haml_loud>
  - if i.subcategs.length > 0
    .row
      - i.subcategs.each do |subcateg|
        - if subcateg.posts.length > 0
          - subcateg.posts.each do |post|
            .col-md-3
              .thumbnail
                %img{alt: "...", height: "200", src: "http://www.binaryturf.com/wp-content/uploads/2011/06/pin-the-post.jpg", width: "300"}/
                .caption
                  %h3= link_to post.name, post_path(post)
                  %p
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  %p
                    = link_to "More", post_path(post), class: "btn btn-primary btn-block"
  %hr/

app/views/categs/new.html.erb
<h1>Create category</h1>

<%= form_for @categ do |f| %>

 <p>Name of category: <br/><%= f.text_field :name %></p>

  <p><%= f.submit "Create new" %></p>

<% end %>

app/views/categs/new.html.haml
%h1 Create category
= render partial: "notifications"
= form_for @categ do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Create new"

app/views/categs/show.html.erb
<h1><%= @categ.name %></h1>

app/views/categs/show.html.haml
%h1
  = @categ.name
/
  <haml_loud> link_to 'Edit', edit_categ_path(@categ), class: "btn btn-small btn-warning" </haml_loud>
  <haml_loud> link_to 'All categories', categs_path, class: "btn btn-small btn-primary" </haml_loud>
- if @categ.subcategs.length > 0
  - @categ.subcategs.each do |subcateg|
    %p
    %h2
      = link_to subcateg.name, subcateg_path(subcateg)
    - if subcateg.posts.length > 0
      .row
        - subcateg.posts.each do |post|
          .col-md-3
            .thumbnail
              %img{alt: "...", height: "200", src: "http://www.binaryturf.com/wp-content/uploads/2011/06/pin-the-post.jpg", width: "300"}/
              .caption
                %h3
                  = link_to post.name, post_path(post)
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                %p
                  = link_to "More", post_path(post), class: "btn btn-primary btn-block"
    %hr/

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= form_for @comment do |f| %>

 <p>Body of comment: <br/><%= f.text_field :body %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/comments/edit.html.haml
%h1 Edit comment
= form_for @comment do |f|
  %p
    Body of comment:
    %br/
    = f.text_field :body
  %p
    = f.submit "Save"

app/views/comments/index.html.erb
<% @comments.each do |i| %>

  <p><%= link_to i.body, comment_path(i) %> <%= link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} %></p>

<% end %>

app/views/comments/index.html.haml
- @comments.each do |i|
  %p
    = link_to i.body, comment_path(i)
    = link_to "Delete", i, method: :delete, data: { confirm: "Delete?"}

app/views/comments/new.html.erb
<h1>Create comment</h1>

<%= form_for @comment do |f| %>

 <p>Body of comment: <br/><%= f.text_field :body %></p>

  <p><%= f.submit "Create new" %></p>

<% end %>

app/views/comments/new.html.haml
%h1 Create comment
= form_for @comment do |f|
  %p
    Body of comment:
    %br/
    = f.text_field :body
  %p
    = f.submit "Create new"

app/views/comments/show.html.erb
<%= @comment.body %>

app/views/comments/show.html.haml
= @comment.body

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-inverse{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a#logo.navbar-brand{href: "/"} Ultra
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li.active
      %li
        %a{href: "/"} Home
      %li
        %a{href: "/pages"} Pages
      %li
        %a{href: "#"} Privacy policy
      %li
        %a{href: "#"} Contacts
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{href: "#"} Sign in

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ultra</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ultra
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield

app/views/pages/_form.html.haml
%p
  Name of page:
  %br/
  = f.text_field :name
%p
  Body of page:
  %br/
  = f.text_field :body

app/views/pages/_notifications.html.haml
%p{style: "color: red;"}
  = flash[:error]

app/views/pages/edit.html.erb
<h1>Edit page</h1>

<%= form_for @page do |f| %>

 <p>Name of page: <br/><%= f.text_field :name %></p>
 <p>Body of page: <br/><%= f.text_field :body %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/pages/edit.html.haml
%h1 Edit page
= render partial: "notifications"
= form_for @page do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Save"

app/views/pages/index.html.erb
<% @pages.each do |i| %>

  <p><%= link_to i.name, page_path(i) %> <%= link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} %></p>

<% end %>

app/views/pages/index.html.haml
%ul.nav.nav-pills.nav-stacked.col-md-8.col-md-offset-2
  - @pages.each do |i|
    %li.active
      = link_to i.name, page_path(i)
      /
        <haml_loud> link_to 'Edit', edit_page_path(i), class: "btn btn-small btn-warning" </haml_loud>
        <haml_loud> link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} </haml_loud>
%hr/
/
  <haml_loud> link_to 'New page', new_page_path(@post), class: "btn btn-small btn-warning" </haml_loud>

app/views/pages/new.html.erb
<h1>Create page</h1>

<%= form_for @page do |f| %>

 <p>Name of page: <br/><%= f.text_field :name %></p>
 <p>Body of page: <br/><%= f.text_field :body %></p>

  <p><%= f.submit "Create new" %></p>

<% end %>

app/views/pages/new.html.haml
%h1 Create page
= render partial: "notifications"
= form_for @page do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Create new"

app/views/pages/show.html.erb
<h1><%= @page.name %></h1>
<%= @page.body %>

app/views/pages/show.html.haml
.col-md-8.col-md-offset-2
  %h1
    = @page.name
  %p
    = @page.body
  %hr/
  %h3 Comments
  - if @page.comments.length > 0
    - @page.comments.each do |comment|
      .alert.alert-info
        = comment.body
  - else
    %h4 No comments have been posted yet.
  %h5 Add comment:
  %form{role: "form"}
    %p
      %textarea.form-control{rows: "3"}
    %button.btn.btn-primary.pull-right{type: "button"} Comment
/
  <h3>Add a comment:</h3>
  <haml_loud> form_for([@page, @page.comments.create(params[:comment])]) do |f| </haml_loud><haml_block>

  <div class="field">
  <haml_loud> f.label :body </haml_loud><br />
  <haml_loud> f.text_area :body </haml_loud>
  </div>
  <div class="actions">
  <haml_loud> f.submit </haml_loud>
  </div>
  </haml_block>
/
  <haml_loud> link_to 'All pages', pages_path, class: "btn btn-small btn-primary" </haml_loud>
  <haml_loud> link_to 'Edit', edit_page_path(@page), class: "btn btn-small btn-warning" </haml_loud>
  <haml_loud> link_to "Delete", @page, method: :delete, data: { confirm: "Delete?"} </haml_loud>

app/views/posts/_form.html.haml
%p
  Name:
  %br/
  = f.text_field :name
%p
  Year:
  %br/
  = f.text_field :year
%p
  Body:
  %br/
  = f.text_field :body
%p
  Size:
  %br/
  = f.text_field :size

app/views/posts/_notifications.html.haml
%p{style: "color: red;"}
  = flash[:error]

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_for @post do |f| %>

 <p>Name: <br/><%= f.text_field :name %></p>
 <p>Year: <br/><%= f.text_field :year %></p>
 <p>Body: <br/><%= f.text_field :body %></p>
 <p>Size: <br/><%= f.text_field :size %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/posts/edit.html.haml
%h1 Edit post
= render partial: "notifications"
= form_for @post do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Save"

app/views/posts/index.html.erb
<% @posts.each do |i| %>

  <p><%= link_to i.name, post_path(i) %> <%= link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} %></p>

<% end %>

app/views/posts/index.html.haml
- @posts.each do |i|
  %p
    = link_to i.name, post_path(i)
    = link_to 'Edit', edit_post_path(i), class: "btn btn-small btn-warning"
    = link_to "Delete", i, method: :delete, data: { confirm: "Delete?"}
%hr/
= link_to 'New post', new_post_path(@post), class: "btn btn-small btn-warning"

app/views/posts/new.html.erb
<h1>Create post</h1>

<%= form_for @post do |f| %>

 <p>Name: <br/><%= f.text_field :name %></p>
 <p>Year: <br/><%= f.text_field :year %></p>
 <p>Body: <br/><%= f.text_field :body %></p>
 <p>Size: <br/><%= f.text_field :size %></p>
  <p><%= f.submit "Create new" %></p>

<% end %>

app/views/posts/new.html.haml
%h1 Create post
= render partial: "notifications"
= form_for @post do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Create new"

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>
<p>Year:<%= @post.year%></p>
<p>Body:<%= @post.body%></p>
<p>Size:<%= @post.size%></p>


<h3>Comments</h3>
<% if @post.comments.length > 0 %>
<% @post.comments.each do |comment| %>

<p class="comment-area">
  <%= comment.body %>
</p><br>
<% end %>
<% else %>
<h4>No comments have been posted yet.</h4>
<% end %>


<hr>
<h3>Add a comment:</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>

<div class="field">
  <%= f.label :body %><br />
  <%= f.text_area :body %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/posts/show.html.haml
.col-md-8.col-md-offset-2
  %h1
    = @post.name
  %p
    %strong Year:
    = @post.year
  %p
    = @post.body
  %p
    %strong Size:
    = @post.size
  %hr/
  %h3 Comments
  - if @post.comments.length > 0
    - @post.comments.each do |comment|
      .alert.alert-info
        = comment.body
  - else
    %h4 No comments have been posted yet.
  %h5 Add comment:
  %form{role: "form"}
    %p
      %textarea.form-control{rows: "3"}
    %button.btn.btn-primary.pull-right{type: "button"} Comment
    %hr/

/
  <h3>Add a comment:</h3>
  <haml_loud> form_for([@post, @post.comments.create(params[:comment])]) do |f| </haml_loud><haml_block>
  <div class="field">
  <haml_loud> f.label :body </haml_loud><br />
  <haml_loud> f.text_area :body </haml_loud>
  </div>
  <div class="actions">
  <haml_loud> f.submit </haml_loud>
  </div>
  </haml_block>
/
  <haml_loud> link_to 'All posts', posts_path, class: "btn btn-small btn-primary" </haml_loud>
  <haml_loud> link_to 'Edit', edit_post_path(@post), class: "btn btn-small btn-info" </haml_loud>
  <haml_loud> link_to "Delete", @post, class: "btn btn-small btn-danger", method: :delete, data: { confirm: "Delete?"} </haml_loud>

app/views/subcategs/_form.html.haml
%p
  Name of subcategory:
  %br/
  = f.text_field :name

app/views/subcategs/_notifications.html.haml
%p{style: "color: red;"}
  = flash[:error]

app/views/subcategs/edit.html.erb
<h1>Edit subcategory</h1>

<%= form_for @subcateg do |f| %>

 <p>Name of subcategory: <br/><%= f.text_field :name %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/subcategs/edit.html.haml
%h1 Edit subcategory
= render partial: "notifications"
= form_for @subcateg do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Save"

app/views/subcategs/index.html.erb
<% @subcategs.each do |i| %>

  <p><%= link_to i.name, subcateg_path(i) %> <%= link_to "Delete", i, method: :delete, data: { confirm: "Delete?"} %></p>

<% end %>

app/views/subcategs/index.html.haml
- @subcategs.each do |i|
  %p
    = link_to i.name, subcateg_path(i)
    = link_to 'Edit', edit_subcateg_path(i), class: "btn btn-small btn-warning"
    = link_to "Delete", i, method: :delete, data: { confirm: "Delete?"}

app/views/subcategs/new.html.erb
<h1>Create subcategory</h1>

<%= form_for @subcateg do |f| %>

 <p>Name of subcategory: <br/><%= f.text_field :name %></p>

  <p><%= f.submit "Create new" %></p>

<% end %>

app/views/subcategs/new.html.haml
%h1 Create subcategory
= render partial: "notifications"
= form_for @subcateg do |f|
  = render partial: "form", locals: { f: f}
  %p
    = f.submit "Create new"

app/views/subcategs/show.html.erb
<h1><%= @subcateg.name %></h1>

app/views/subcategs/show.html.haml
%h1
  = @subcateg.name
/
  <haml_loud> link_to 'Edit', edit_subcateg_path(@subcateg), class: "btn btn-small btn-warning" </haml_loud>
  <haml_loud> link_to 'All subcategories', subcategs_path, class: "btn btn-small btn-primary" </haml_loud>
- if @subcateg.posts.length > 0
  - @subcateg.posts.each do |post|
    .col-md-3
      .thumbnail
        %img{alt: "...", height: "200", src: "http://www.binaryturf.com/wp-content/uploads/2011/06/pin-the-post.jpg", width: "300"}/
        .caption
          %h3
            = link_to post.name, post_path(post)
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          %p
            = link_to "More", post_path(post), class: "btn btn-primary btn-block"
- else
  %h4 No posts.
%hr/